### ISSUE TITLE
FYI – registry-js fails to install on some systems

### ISSUE THREAD

**Issue by mattdesl** [juliangruber/downloads-folder#12]
I've had some users complaining of broken installs (https://github.com/mattdesl/workshop-generative-art/issues/10, https://github.com/mattdesl/canvas-sketch/issues/96), I finally tracked it down to this module (more specifically, `registry-js` failing). In my case I plan to replace this with another solution that doesn't rely on Windows registry access, but wanted to just bring this to your attention so you are aware of the issue!

Cheers

**Comment by juliangruber** [comment]
I've made the dependency optional and published a new major release. Thanks for reporting and keep up the great work!
