### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by c4kaci** [juliangruber/downloads-folder#23]
What is exact webpack specification for your package?
I have these errors:

> ERROR in ./node_modules/downloads-folder/index.js
> Module not found: Error: Can't resolve 'child_process' in 'E:\Develop\Photoshop\UXP\c4-uxp-photoshop-plugin-spectrum-with-pure-javascript\node_modules\downloads-folder'
>  @ ./node_modules/downloads-folder/index.js 4:17-41
>  @ ./src/c4.js
>  @ ./src/actions.js
>  @ ./src/index.js

> ERROR in ./node_modules/downloads-folder/index.js
> Module not found: Error: Can't resolve 'fs' in 'E:\Develop\Photoshop\UXP\c4-uxp-photoshop-plugin-spectrum-with-pure-javascript\node_modules\downloads-folder'
>  @ ./node_modules/downloads-folder/index.js 5:17-30
>  @ ./src/c4.js
>  @ ./src/actions.js
>  @ ./src/index.js

> ERROR in ./node_modules/registry-js/build/Release/registry.node 1:2
> Module parse failed: Unexpected character '�' (1:2)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
>  @ ./node_modules/registry-js/dist/lib/registry.js 5:6-50
>  @ ./node_modules/registry-js/dist/lib/index.js
>  @ ./node_modules/downloads-folder/index.js
>  @ ./src/c4.js
>  @ ./src/actions.js
>  @ ./src/index.js

Thx
Karoly

**Comment by juliangruber** [comment]
It needs access to the `child_process` and `fs` modules from node core, and it looks like there's another error for which you could ask in the issue tracker of https://ghub.io/registry-js

**Comment by c4kaci** [comment]
After 
> npm i child_process
> npm i fs
> npm install --save registry-js

I  get same errors
I missed something?

**Comment by juliangruber** [comment]
Ok that's not it. Check this out: https://stackoverflow.com/a/65556946

**Comment by juliangruber** [comment]
You don't need to manually install any of these modules btw

**Comment by c4kaci** [comment]
I checked stackoverflow issue.
"fallback" option depricated if that's what you thought 

Manually installed packages uninstalled

**Comment by juliangruber** [comment]
I think at this point it's a webpack question. Please open an issue on their issue tracker

**Comment by juliangruber** [comment]
check how in the stackoverflow issue they're adding a webpack plugin, that should help.

Also, why do you use webpack with this module in the first place?

**Comment by c4kaci** [comment]
Thank you Julian.

**Comment by juliangruber** [comment]
Are you trying to run this in a browser? :thinking:

**Comment by c4kaci** [comment]
No this a Photoshop UXP plugin which run on embedded node.js engine. 
It does not use browswert. 
I suffer quite a bit from it.
