### ISSUE TITLE
Doesn't track windows download's folder move

### ISSUE THREAD

**Issue by brubsby** [juliangruber/downloads-folder#5]
![image](https://user-images.githubusercontent.com/57653502/74208340-bcf8ce00-4c48-11ea-90c3-529d8737b169.png)

On windows it's possible to move your downloads folder to a drive that your user folder isn't on, and in this situation this package will point to the incorrect downloads location. Unsure if there's an easy way to find this new location with node however.

**Comment by tobimori** [comment]
Should be possible.
https://www.npmjs.com/package/windows-registry + Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders{374DE290-123F-4565-9164-39C4925E467B}

Would also fix the backslash bug I just pr'd a temp fix for.

**Comment by juliangruber** [comment]
Would you like to create a PR for this?

**Comment by tobimori** [comment]
done #8

**Comment by juliangruber** [comment]
https://github.com/juliangruber/downloads-folder/releases/tag/v1.0.4
